# Generated by Django 6.0.3 on 2026-04-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='duracion',
            field=models.IntegerField(default=45, help_text='Duración en minutos'),
        ),
        migrations.AddField(
            model_name='rutina',
            name='tipo_entrenamiento',
            field=models.CharField(choices=[('crossfit', 'CrossFit'), ('fuerza', 'Fuerza'), ('cardio', 'Cardio'), ('funcional', 'Funcional'), ('hipertrofia', 'Hipertrofia'), ('flexibilidad', 'Flexibilidad')], default='funcional', max_length=20),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
