# Generated by Django 6.0.3 on 2026-04-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0003_rutina_duracion_rutina_tipo_entrenamiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutinaejercicio',
            options={'ordering': ['orden']},
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='grupo_muscular',
            field=models.CharField(choices=[('pecho', 'Pecho'), ('espalda', 'Espalda'), ('hombros', 'Hombros'), ('biceps', 'Bíceps'), ('triceps', 'Tríceps'), ('piernas', 'Piernas'), ('gluteos', 'Glúteos'), ('core', 'Core'), ('cardio', 'Cardio')], default='core', max_length=20),
        ),
        migrations.AddField(
            model_name='rutina',
            name='creada_en',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutina',
            name='dias',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rutina',
            name='nivel',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=20),
        ),
        migrations.AddField(
            model_name='rutinaejercicio',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='duracion',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='repeticiones',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='rutinaejercicio',
            name='series',
            field=models.IntegerField(default=3),
        ),
    ]
