# Generated by Django 6.0.3 on 2026-05-03 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0004_alter_rutinaejercicio_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_real', models.IntegerField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='rutinas.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SerieSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.IntegerField(default=1)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('repeticiones_realizadas', models.IntegerField(default=0)),
                ('tiempo_descanso', models.IntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
                ('rutina_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_sesion', to='rutinas.rutinaejercicio')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='rutinas.sesionentrenamiento')),
            ],
            options={
                'ordering': ['numero_serie'],
            },
        ),
    ]
