# Generated by Django 6.0.3 on 2026-05-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0005_sesionentrenamiento_seriesesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ejercicios/'),
        ),
    ]
