# Generated by Django 6.0.3 on 2026-05-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0006_ejercicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link de YouTube o TikTok', null=True),
        ),
    ]
