# Generated by Django 6.0.3 on 2026-05-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0007_ejercicio_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Link externo de imagen o GIF', null=True),
        ),
    ]
