# Generated by Django 6.0.3 on 2026-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0008_ejercicio_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='video_url',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ejercicios/videos/'),
        ),
    ]
