# Generated by Django 6.0.3 on 2026-05-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0009_remove_ejercicio_imagen_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='equipamiento/')),
            ],
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='equipamiento',
            field=models.ManyToManyField(blank=True, to='rutinas.equipamiento'),
        ),
    ]
