# Generated by Django 6.0.3 on 2026-05-06 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0010_equipamiento_ejercicio_equipamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='descripcion',
        ),
    ]
