# Generated by Django 6.0.3 on 2026-05-06 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutinas', '0011_remove_ejercicio_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='equipamiento',
        ),
        migrations.DeleteModel(
            name='Equipamiento',
        ),
    ]
